services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    image: customer-churn-api:latest

    ports:
      - "8000:8000"

    env_file:
      - .env

    restart: unless-stopped

    depends_on:
      mlflow:
        condition: service_started

    networks:
      - customer-churn-network

  mlflow:
    build:
      context: .
      dockerfile: docker/mlflow/Dockerfile

    image: customer-churn-mlflow:latest

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${MLFLOW_PORT}:5000"

    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - mlflow_artifacts:/mlflow/artifacts

    networks:
      - customer-churn-network

  mysql:
    image: mysql:8.4

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_PORT}"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - customer-churn-network

volumes:
  mysql_data:
  mlflow_artifacts:

networks:
  customer-churn-network:
    driver: bridge
