[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py

addopts =
    -v
    --cov=src
    --cov=app
    --cov-report=term-missing
    --cov-report=html

filterwarnings =
    ignore:Setting the shape on a NumPy array has been deprecated:DeprecationWarning