random_state: 42
test_size: 0.2

model_trainer:
  evaluation_metric: roc_auc

  models:
    logistic_regression:
      enabled: true
      max_iter: 1000
      random_state: 42

    decision_tree:
      enabled: true
      criterion: gini
      max_depth: 10
      random_state: 42

    random_forest:
      enabled: true
      n_estimators: 300
      max_depth: 12
      min_samples_split: 5
      min_samples_leaf: 2
      random_state: 42

    gradient_boosting:
      enabled: true
      learning_rate: 0.1
      n_estimators: 200
      max_depth: 3
      random_state: 42

    adaboost:
      enabled: true
      n_estimators: 200
      learning_rate: 1.0
      random_state: 42

    extra_trees:
      enabled: true
      n_estimators: 300
      max_depth: 12
      random_state: 42

model_evaluation:
  experiment_name: Customer_Churn_Classification

  run_name: Production_Run

  log_model: true

  register_model: true

  registered_model_name: CustomerChurnModel
